### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by JoopAue** [RxVisualSedimentation/RxVisualSedimentation#13]
Found this link:
http://gamedevelopment.tutsplus.com/tutorials/how-to-create-a-custom-2d-physics-engine-the-basics-and-impulse-resolution--gamedev-6331

I think it will be sufficient for now.

**Comment by AlpineMutts** [comment]
Looks like a lot of fun! :sweat_smile: 

Thanks, that looks really helpful though!

**Comment by AlpineMutts** [comment]
The tutorial is great, but I don't think we will be able to do this within the given time-frame. This will be a project by itself(also possible, but we'll have to discuss this with Georgi). I think we might have to actually move to a third party for doing this. Box2d or something [similar](http://google.github.io/liquidfun/).

**Comment by JoopAue** [comment]
I agree with you.
Although I don't think the tutorial will be that hard as I worked through it partly.

**Comment by AlpineMutts** [comment]
Sure, let's take a look on Friday.

**Comment by JoopAue** [comment]
I think we can find some reactive way of implementing it. 
However as you said, let's talk to Georgi about it as well!

**Comment by JoopAue** [comment]
See #16

**Comment by AlpineMutts** [comment]
Basic implementation works. Closing this, more detailed issues on this in the future.
