### ISSUE TITLE
Example - Create a force which attracts the circles to the rectangle.

### ISSUE THREAD

**Issue by AlpineMutts** [RxVisualSedimentation/RxVisualSedimentation#2]
The idea is to create a force which should attract the circles. Implement this for our example.

**Comment by AlpineMutts** [comment]
A very handy example, which we can use for this seems to be the following example: 
http://bl.ocks.org/mbostock/1021841

Don't know how easy it will be to make an object static in the environment though.

**Comment by AlpineMutts** [comment]
Seems like we also need to use the [matter.js](https://github.com/liabru/matter-js) library in order to actually create physics-like attraction. For example for the bar graphs.

**Comment by AlpineMutts** [comment]
Just created this: http://jsfiddle.net/Ldo3hk0g/1/
![image](https://cloud.githubusercontent.com/assets/1066157/6190269/eb21845c-b3a0-11e4-9cb5-9c498fab0a33.png)

So I think depending on our chart behaviour we should use matter-js or d3-js. The only needed functionality from matter-js is downward gravity right now. I think it might be a good idea to make sure that we really can't do it with d3-js, possibly ask someone over there. Since otherwise our library will become bloated making unnecessary use of multiple other libraries.

**Comment by AlpineMutts** [comment]
In order to change the circles over time we either need to create our own custom [bodies](https://github.com/liabru/matter-js/blob/master/src/body/Body.js) or make a custom [renderer](https://github.com/liabru/matter-js/blob/master/src/render/Render.js) for matter-js.

**Comment by AlpineMutts** [comment]
Updated with randomization of circles:
http://jsfiddle.net/Ldo3hk0g/3/

**Comment by JoopAue** [comment]
outdated as we took a different approach
