### ISSUE TITLE
Monads, Monads Everywhere

### ISSUE THREAD

**Issue by JoopAue** [RxVisualSedimentation/RxVisualSedimentation#35]
I think we can introduce Monads here to make our life easier. Well easier when we figure out how to use them and what they do.
I think that the Maybe monad is appropriate. 

``` javascript
var obtainCollisions = function(pairs){
  var collisions = [];
  pairs.map(function(pair){
    var collision = new Collision(pair.a, pair.b, null, null);
    var collided = collision.circleVsCircle();
    if (collided) {
      collisions.push(collision);
    }
  });
  return collisions;
};
```

http://modernjavascript.blogspot.nl/2013/06/monads-in-plain-javascript.html <- May not be correct according to the comments

https://curiosity-driven.org/monads-in-javascript

**Comment by AlpineMutts** [comment]
Maybe the maybe Monad is appropriate indeed. 

![maybe](http://media.giphy.com/media/yjukPn2GGbMC4/giphy.gif)

**Comment by JoopAue** [comment]
[Monad and Functor](https://github.com/RxVisualSedimentation/RxVisualSedimentation/wiki/Resources)

**Comment by AlpineMutts** [comment]
I'm reading it now. Then we'll be on the same page with this again.

**Comment by JoopAue** [comment]
We haven't found a proper use for this, so will be closing this for now.
