### ISSUE TITLE
Do we even need D3.JS?

### ISSUE THREAD

**Issue by JoopAue** [RxVisualSedimentation/RxVisualSedimentation#39]
As far as I can tell we only use D3.js as a wrapper for creating an svg container and adding elements to it. 
We may be able to refactor it out all together.

http://stackoverflow.com/questions/20539196/creating-svg-elements-dynamically-with-javascript-inside-html

**Comment by AlpineMutts** [comment]
Yeah, I wanted to do this eventually. I believe the time has come.

**Comment by JoopAue** [comment]
For now we will keep it in there.
It is too much for now to refactor it out.
