### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by JoopAue** [RxVisualSedimentation/RxVisualSedimentation#46]
This is what we want:

http://ahoj.io/nodejs-and-websocket-simple-chat-tutorial

**Comment by AlpineMutts** [comment]
Still have to read carefully through this, but it looks exactly like what we're looking for.

**Comment by JoopAue** [comment]
Multiple options:
http://stackoverflow.com/questions/16392260/which-websocket-library-to-use-with-node-js

Socket.io looks interesting as well.
http://socket.io/

**Comment by JoopAue** [comment]
#48
