### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by JoopAue** [RxVisualSedimentation/RxVisualSedimentation#49]
To do
- Two presentation points
- ~~Monads~~
- Input fields (reactive): topics, ~~gravity, delta radius, restitution,~~ reset, ~~time/ms.~~ (cant do)
- Websocket request tweets of type.
- control messages for server from client
- back pressure

Idea
- 2 teams. 2 colors. websockets, click game.
- Erik Meijerfy

**Comment by JoopAue** [comment]
http://reactivex.io/documentation/operators/defer.html

**Comment by JoopAue** [comment]
http://reactivex.io/documentation/operators/groupby.html
This is exactly what we want for the messages that come from the server.
We attach a keyword to each tweet and we have the groupby operator emit new observables for each keyword.

**Comment by JoopAue** [comment]
We could also count the number of new tweets per state update and spawn a body with a radius related to the amount. Just a thought, we don't have to do this

**Comment by JoopAue** [comment]
http://reactivex.io/documentation/operators/from.html
fromEvent ... makes much more sense then the wrapper we use right now.

**Comment by JoopAue** [comment]
Epicness:
http://jaredly.github.io/rxvision/examples/playground/

**Comment by AlpineMutts** [comment]
Nice, that looks great! I just got everything working. I have put everything into one observable right now, that way we can use the groupby operator later. So right now when you subscribe to two topics you get both topics in a single ballstream.

So: it's now possible to subscribe and unsubscribe topics by passing messages from the client to the server via WebSockets. This in turn results in multiple twitterclient streams emitting events.

We'll have to probably watch out with how many topics we can request at once from twitter. I get the 'Easy there, Turbo. Too many requests recently. Enhance your calm.' message more often now.

**Comment by AlpineMutts** [comment]
> We could also count the number of new tweets per state update and spawn a body with a radius related to the amount. Just a thought, we don't have to do this

I like the way it is now though, it's really responsive. Maybe we can make this a mode you can toggle?

**Comment by JoopAue** [comment]
Merge to combine observables before sending messages to the server

**Comment by JoopAue** [comment]
We should make the mass dependent on the size.
Got 1 pixel circles pushing 100px circles like its nothing.

**Comment by AlpineMutts** [comment]
Yeah I already did that today, we'll merge it in tomorrow.
